{"name": "Проверка: если попытаться создать курьера с данными, идентичными уже существующему, вернётся ошибка 409", "status": "passed", "description": "(!)В тестовой документации указан только текст для ошибки с одинаковым логином «Этот логин уже используется», в случае если у курьеров совпадают ВСЕ данные, фактически возвращается ошибка с таким же сообщением. Это серая зона в требованиях (как мне кажется), поэтому в тесте проверяем только код ошибки", "start": 1710697530782, "stop": 1710697531766, "uuid": "04e46023-0df2-427b-b58b-4a80b39e51fa", "historyId": "78f01f5c08479b51ea623e68a0264311", "testCaseId": "78f01f5c08479b51ea623e68a0264311", "fullName": "tests.tests_courier.test_create_courier.TestCreateCourier#test_create_two_same_couriers_causes_409_error", "labels": [{"name": "parentSuite", "value": "tests.tests_courier"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "Olyas-MacBook-Air.local"}, {"name": "thread", "value": "94503-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_courier.test_create_courier"}]}