{"name": "Проверка: если не передать id, вернётся ошибка 400", "status": "passed", "description": "(!)Тест падает, т.к. приходит ошибка 404, а не 400", "start": 1710504308424, "stop": 1710504308985, "uuid": "b411b942-1bc8-4353-8b48-457665623616", "historyId": "0b194bc681249f4a894c19eaac46cb90", "testCaseId": "0b194bc681249f4a894c19eaac46cb90", "fullName": "tests.tests_courier.test_delete_courier.TestDeleteCourier#test_delete_courier_with_invalid_id_causes_404_error", "labels": [{"name": "parentSuite", "value": "tests.tests_courier"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "Olyas-MacBook-Air.local"}, {"name": "thread", "value": "78521-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_courier.test_delete_courier"}]}